name: FeatherJump
version: 1.0.0
main: com.rndunel.jumpfeather.FeatherJump
description: A feather
author: rbdunel
website: https://github.com/SwiftCris
api-version: '1.20.6'
commands:
 fly:
  usage: /<fly> [player]
  permission: fly.command
  permission-message: You do not have permission to run this command
